config/routes.rb
Rails.application.routes.draw do
  root "sessions#home"
  
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'

  resources :cues
  resources :puppies
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cue.rb
class Cue < ApplicationRecord
  belongs_to :puppy
end

app/models/puppy.rb
class Puppy < ApplicationRecord
  belongs_to :user
  has_many :cues
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :puppies, dependent: :delete_all

  validates  :username, presence: true, uniqueness: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user 
  helper_method :logged_in?
  helper_method :find_user
  helper_method :find_puppy
  
  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end

  def redirect_if_not_logged_in
    redirect_to '/' if !logged_in?
  end
  
  def find_user
    @user = User.find(params[:id])
  end

  def find_puppy 
    @puppy = Puppy.find(params[:id])
  end
end

app/controllers/cues_controller.rb
class CuesController < ApplicationController
end

app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController

  def index 
    @puppies = Puppy.all
    #@puppies = current_user.puppies.all
  end 

  def new 
    @puppy = Puppy.new 
    @user = @puppy.build_user
  end

  def create 
    @puppy = current_user.puppies.create(puppy_params)
    if @puppy.save 
      redirect_to puppy_path(@puppy)
    else  
      render :new
    end
  end

  def show 
    find_puppy
  end

  def edit 
    find_puppy
  end

  def update 
    find_puppy
    @puppy.update(puppy_params)
    redirect_to puppy_path(@puppy)
  end

  private 

  def puppy_params 
    params.require(:puppy).permit(:name, :breed, :location, :bio, :user_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def home 
  end

  def login 
  end

  def create 
    user = User.find_by(username: params[:user][:username])
    
    if user && user.authenticate(params[:user][:password])
      session[:user_id] = user.id
      redirect_to user_path(user) # '/users/#{user.id}'
    else  
      flash[:message] = "Invalid Login Info, Please Try Again"
      redirect_to '/login'
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new 
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else  
      render :new
    end
  end

  def show 
    @user = User.find_by_id(params[:id]) 
    redirect_to '/' if !@user
  end 
  
  private 

  def user_params 
    params.require(:user).permit(:email, :username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cues_helper.rb
module CuesHelper
end

app/helpers/puppies_helper.rb
module PuppiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PuppyPortal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/puppies/edit.html.erb
Edit details here



<h1>Edit details for <%= @puppy.name %></h1>

<% if @puppy.errors.any? %>
  <ul>
    <% @puppy.errors.full_messages.each do |message| %>
     
      <li><%= message %></li>
    <%end%>
</ul>
<% end %>

<%= form_for @puppy do |f| %>

  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  
  <%= f.label :breed %><br>
  <%= f.text_field :breed %><br>
  <%= f.label :location %><br>
  <%= f.text_field :location %><br>
  <%= f.label :bio %><br>
  <%= f.text_field :bio %><br>

  <%= f.submit "Update Details", :class => 'btn btn-success btn-sm' %>
 
 <% end %>

app/views/puppies/index.html.erb
<h1>Puppy Portal Puppies!</h1><br />

<% @puppies.each do |puppy| %>
<ul>  <%= link_to puppy.name, puppy_path(puppy)  %> </ul>
 <% end %>

app/views/puppies/new.html.erb
<h1>Add a Puppy</h1>

<% if @puppy.errors.any? %>
  <ul>
    <% @puppy.errors.full_messages.each do |message| %>
     
      <li><%= message %></li>
    <%end%>
</ul>
<% end %>

<%= form_for @puppy do |f| %>
  
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  
  <%= f.label :breed %><br>
  <%= f.text_field :breed %><br>
  <%= f.label :location %><br>
  <%= f.text_field :location %><br>
  <%= f.label :bio %><br>
  <%= f.text_field :bio %><br>

  <%= f.submit "Add Puppy", :class => 'btn btn-success btn-sm' %>
 
 <% end %>

app/views/puppies/show.html.erb
<h1><%= @puppy.name %>'s Page</h1>

  <p>I'm a <%= @puppy.breed %> </p><br>
  
  <p>I live in <%= @puppy.location %> </p><br>
  
  <p><%= @puppy.bio %></p><br>
  

<p><%= link_to "Edit Details", edit_puppy_path(@puppy) %></p>

app/views/users/index.html.erb
<h1>User index</h1>

app/views/users/new.html.erb
<h1>Users form</h1>

<h1>Sign Up</h1>


<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <br>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.submit "Submit", :class => 'btn btn-success btn-sm' %>
<% end %>

app/views/users/show.html.erb
<h1>Hello, <%= @user.username %></h1>

this is a user's personal page where they can add/edit/delete a puppy

<% if current_user.puppies.length == 0 %>
<h3>You don't have any puppies :(</h3>
<p>Click <%= link_to "here", new_puppy_path %> to add a puppy! </p>
<% else %>
<p>shows puppy or puppies and will have links to the puppy profile</p>
<% current_user.puppies.each do |puppy| %>
<ul><%= link_to puppy.name, puppy_path(puppy)  %> </ul>
<% end %>
<% end %>